### ISSUE TITLE
makeSurveyDB.py - Unsure what the following code is doing

### ISSUE THREAD

**Issue by harneyp2** [wicount/WiCount#2]
@velcro-ie the following code has a for loop that looks bizarre. Can you explain what is going on or fix/simplify

`elif data[0] == "Time":
                # if the first cell is Time this row contains the capacity of the room
                # Update the room table with these details and get the room ID from the room table
                if len(occupancyDetails) == 1:
                    details = []
                    for x in range(2, len(data),1):
                        #details.append(data[x]) this is wrong.
                        details.append(0)
                    occupancyDetails.append(details)
                    print(details)
                    roomIDs = UpdateRoomTable(occupancyDetails)`

**Comment by velcro-ie** [comment]
We need to ensure that every room in the survey data is in the room table.  As the capacity details in the survey table are wrong this code ensures that the room is in the table and sets the capacity to zero for the room.  

Code is commented to show this
